
import com.formdev.flatlaf.*;
import com.toedter.calendar.*;

import java.awt.*;
import java.awt.event.*;
import java.text.*;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.logging.*;
import javax.swing.*;
import javax.swing.table.*;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author china
 */
public class TaskFrame extends javax.swing.JFrame {

    ThemeManager themeManager = new ThemeManager();
    TaskManager taskManager = new TaskManager();
    FileHandler fileHandler = new FileHandler("txtFiles/data.txt");

    /**
     * Creates new form TaskFrame
     */
    public TaskFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        
        themeManager.transparentButton(EditTaskSearchBtn);
        themeManager.transparentButton(DeleteBackBtn);
        themeManager.transparentButton(DeleteFowardBtn);
        themeManager.transparentButton(MarkDoneBackBtn);
        themeManager.transparentButton(MarkDoneFowardBtn);

        /// Show AddTaskPnl by default
        setPanel(AddTaskPnl, new Dimension(450, 500));
        this.pack();
        
    }

    private void displayTasks(ArrayList<Task> tasks) {
        // Define column names
        String[] columns = {"Task ID", "Task Name", "Subject", "Due Date", "Due At", "Priority", "Status"};

        // Create model with 0 initial rows
        DefaultTableModel todayModel = new DefaultTableModel(columns, 0);

        // Fill the model
        for (Task task : tasks) {
            todayModel.addRow(new Object[]{
                    task.getTaskID(),
                    task.getTaskName(),
                    task.getSubject(),
                    task.getDueDate().format(DateTimeFormatter.ofPattern("dd MM yyyy")),
                    task.getDueTime().format(DateTimeFormatter.ofPattern("HH:mm")),
                    task.getPriority(),
                    task.getStatus()
            });
        }

        // Apply model to table
        jTable1.setModel(todayModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddTaskIcn = new javax.swing.JLabel();
        AddTaskPnl = new javax.swing.JPanel();
        TaskNamelbl = new javax.swing.JLabel();
        TaskName = new javax.swing.JTextField();
        Subjectlbl = new javax.swing.JLabel();
        Subject = new javax.swing.JTextField();
        DueDatelbl = new javax.swing.JLabel();
        DateChooser = new com.toedter.calendar.JDateChooser();
        DueTime = new javax.swing.JLabel();
        HourChooser = new javax.swing.JComboBox<>();
        MinuteChooser = new javax.swing.JComboBox<>();
        Prioritylbl = new javax.swing.JLabel();
        PriorityChooser = new javax.swing.JComboBox<>();
        Statuslbl = new javax.swing.JLabel();
        StatusChooser = new javax.swing.JComboBox<>();
        AddTaskBtn = new javax.swing.JButton();
        AddTaskBG = new javax.swing.JLabel();
        EditTaskIcn = new javax.swing.JLabel();
        EditTaskPnl = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        EditTaskSearchFld = new javax.swing.JTextField();
        EditTaskSearchBtn = new javax.swing.JButton();
        EditTaskBtn = new javax.swing.JButton();
        BG1 = new javax.swing.JLabel();
        DeleteTaskIcn = new javax.swing.JLabel();
        DeleteTaskPnl = new javax.swing.JPanel();
        DeleteTaskSearchFld = new javax.swing.JTextField();
        TaskNamelbl1 = new javax.swing.JLabel();
        Subjectlbl1 = new javax.swing.JLabel();
        DueDatelbl1 = new javax.swing.JLabel();
        DueTime1 = new javax.swing.JLabel();
        Prioritylbl1 = new javax.swing.JLabel();
        Statuslbl1 = new javax.swing.JLabel();
        DeleteTaskBtn = new javax.swing.JButton();
        DeleteBackBtn = new javax.swing.JButton();
        DeleteFowardBtn = new javax.swing.JButton();
        DeleteTaskBG = new javax.swing.JLabel();
        MarkDoneTaskIcn = new javax.swing.JLabel();
        MarkDonePnl = new javax.swing.JPanel();
        MarkDoneSearchFld = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TaskNamelbl2 = new javax.swing.JLabel();
        Subjectlbl2 = new javax.swing.JLabel();
        DueDatelbl2 = new javax.swing.JLabel();
        DueTime2 = new javax.swing.JLabel();
        Prioritylbl2 = new javax.swing.JLabel();
        Statuslbl2 = new javax.swing.JLabel();
        MarkDoneBackBtn = new javax.swing.JButton();
        MarkDoneBtn = new javax.swing.JButton();
        MarkDoneFowardBtn = new javax.swing.JButton();
        MarkDoneBG = new javax.swing.JLabel();
        TaskFrameBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(550, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddTaskIcn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        AddTaskIcn.setToolTipText("Add Task");
        AddTaskIcn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddTaskIcnMouseClicked(evt);
            }
        });
        getContentPane().add(AddTaskIcn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 60, -1, -1));

        AddTaskPnl.setName(""); // NOI18N
        AddTaskPnl.setOpaque(false);
        AddTaskPnl.setPreferredSize(new java.awt.Dimension(350, 500));
        AddTaskPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TaskNamelbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TaskNamelbl.setText("Task Name :");
        TaskNamelbl.setPreferredSize(new java.awt.Dimension(110, 30));
        AddTaskPnl.add(TaskNamelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, 110, 40));

        TaskName.setPreferredSize(new java.awt.Dimension(210, 40));
        AddTaskPnl.add(TaskName, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 25, -1, -1));

        Subjectlbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Subjectlbl.setText("Subject       :");
        Subjectlbl.setPreferredSize(new java.awt.Dimension(120, 40));
        AddTaskPnl.add(Subjectlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 75, 110, -1));

        Subject.setPreferredSize(new java.awt.Dimension(210, 40));
        AddTaskPnl.add(Subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 75, -1, -1));

        DueDatelbl.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        DueDatelbl.setText("Due Date    :");
        DueDatelbl.setPreferredSize(new java.awt.Dimension(110, 40));
        AddTaskPnl.add(DueDatelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 125, 110, -1));

        DateChooser.setToolTipText("Date : dd/MM/yyyy");
        DateChooser.setMinSelectableDate(new java.util.Date(1577829600000L));
        AddTaskPnl.add(DateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 125, 210, 40));

        DueTime.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        DueTime.setText("Due Time    :");
        DueTime.setPreferredSize(new java.awt.Dimension(110, 40));
        AddTaskPnl.add(DueTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 175, 110, -1));

        HourChooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        HourChooser.setToolTipText("Hours");
        HourChooser.setPreferredSize(new java.awt.Dimension(70, 40));
        AddTaskPnl.add(HourChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 175, -1, -1));

        MinuteChooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        MinuteChooser.setToolTipText("Minutes");
        MinuteChooser.setPreferredSize(new java.awt.Dimension(70, 40));
        AddTaskPnl.add(MinuteChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 175, -1, -1));

        Prioritylbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Prioritylbl.setText("Priority      :");
        AddTaskPnl.add(Prioritylbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 225, 110, 40));

        PriorityChooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "High", "Medium", "Low" }));
        AddTaskPnl.add(PriorityChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 225, 140, 40));

        Statuslbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Statuslbl.setText("Status        :");
        AddTaskPnl.add(Statuslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 275, 110, 40));

        StatusChooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Complete", "Pending", "Overdue" }));
        AddTaskPnl.add(StatusChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 275, 140, 40));

        AddTaskBtn.setBackground(new Color(30,31,38, 128));
        AddTaskBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AddTaskBtn.setText("Add Task");
        AddTaskBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTaskBtnActionPerformed(evt);
            }
        });
        AddTaskPnl.add(AddTaskBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, 40));

        AddTaskBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lightThemeIcons/BACKGROUND.png"))); // NOI18N
        AddTaskBG.setToolTipText("");
        AddTaskPnl.add(AddTaskBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 400, 550));

        getContentPane().add(AddTaskPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        EditTaskIcn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        EditTaskIcn.setToolTipText("Edit Task");
        EditTaskIcn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditTaskIcnMouseClicked(evt);
            }
        });
        getContentPane().add(EditTaskIcn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 170, -1, -1));

        EditTaskPnl.setPreferredSize(new java.awt.Dimension(750, 500));
        EditTaskPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new Color(40,40,40,128));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(700, 395));

        jTable1.setBackground(new Color(40,40,40,128));
        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Task ID", "Task Name", "Task Subject", "Due Date", "Due Time", "Priority", "Staus"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(24);
        jTable1.setShowGrid(false);
        jTable1.setShowVerticalLines(true);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(1);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(5);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(5);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(5);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(5);
        }

        EditTaskPnl.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 0, -1, -1));

        EditTaskSearchFld.setBackground(new Color(40,40,40,128));
        EditTaskSearchFld.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EditTaskSearchFld.setForeground(new java.awt.Color(255, 255, 255));
        EditTaskSearchFld.setToolTipText("Search");
        EditTaskSearchFld.setPreferredSize(new java.awt.Dimension(155, 40));
        EditTaskSearchFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditTaskSearchFldActionPerformed(evt);
            }
        });
        EditTaskPnl.add(EditTaskSearchFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 410, -1, -1));

        EditTaskSearchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lightThemeIcons/search.png"))); // NOI18N
        EditTaskSearchBtn.setMaximumSize(new java.awt.Dimension(30, 30));
        EditTaskSearchBtn.setMinimumSize(new java.awt.Dimension(30, 30));
        EditTaskSearchBtn.setPreferredSize(new java.awt.Dimension(40, 40));
        EditTaskSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditTaskSearchBtnActionPerformed(evt);
            }
        });
        EditTaskPnl.add(EditTaskSearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 410, -1, -1));

        EditTaskBtn.setBackground(new Color(40,40,40,128));
        EditTaskBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EditTaskBtn.setText("Edit Tasks");
        EditTaskBtn.setPreferredSize(new java.awt.Dimension(120, 40));
        EditTaskBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditTaskBtnActionPerformed(evt);
            }
        });
        EditTaskPnl.add(EditTaskBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 410, -1, -1));

        BG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lightThemeIcons/BACKGROUND.png"))); // NOI18N
        BG1.setToolTipText("");
        EditTaskPnl.add(BG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 800, 550));

        getContentPane().add(EditTaskPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        DeleteTaskIcn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        DeleteTaskIcn.setToolTipText("Delete Task");
        DeleteTaskIcn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteTaskIcnMouseClicked(evt);
            }
        });
        getContentPane().add(DeleteTaskIcn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 280, -1, -1));

        DeleteTaskPnl.setPreferredSize(new java.awt.Dimension(350, 500));
        DeleteTaskPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DeleteTaskSearchFld.setBackground(new Color(40,40,40,128));
        DeleteTaskSearchFld.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeleteTaskSearchFld.setForeground(new java.awt.Color(255, 255, 255));
        DeleteTaskSearchFld.setToolTipText("Search");
        DeleteTaskSearchFld.setPreferredSize(new java.awt.Dimension(150, 30));
        DeleteTaskSearchFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteTaskSearchFldActionPerformed(evt);
            }
        });
        DeleteTaskPnl.add(DeleteTaskSearchFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 10, -1, -1));

        TaskNamelbl1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TaskNamelbl1.setText("Task Name :");
        TaskNamelbl1.setPreferredSize(new java.awt.Dimension(110, 30));
        DeleteTaskPnl.add(TaskNamelbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 380, 40));

        Subjectlbl1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Subjectlbl1.setText("Subject       :");
        Subjectlbl1.setPreferredSize(new java.awt.Dimension(120, 40));
        DeleteTaskPnl.add(Subjectlbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 380, -1));

        DueDatelbl1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DueDatelbl1.setText("Due Date    :");
        DueDatelbl1.setPreferredSize(new java.awt.Dimension(110, 40));
        DeleteTaskPnl.add(DueDatelbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 380, -1));

        DueTime1.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        DueTime1.setText("Due Time    :");
        DueTime1.setPreferredSize(new java.awt.Dimension(110, 40));
        DeleteTaskPnl.add(DueTime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 380, -1));

        Prioritylbl1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Prioritylbl1.setText("Priority      :");
        Prioritylbl1.setPreferredSize(new java.awt.Dimension(98, 40));
        DeleteTaskPnl.add(Prioritylbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 380, 40));

        Statuslbl1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Statuslbl1.setText("Status        :");
        DeleteTaskPnl.add(Statuslbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 380, 40));

        DeleteTaskBtn.setBackground(new Color(40,40,40,128));
        DeleteTaskBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DeleteTaskBtn.setText("DELETE TASK");
        DeleteTaskBtn.setPreferredSize(new java.awt.Dimension(150, 40));
        DeleteTaskBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteTaskBtnActionPerformed(evt);
            }
        });
        DeleteTaskPnl.add(DeleteTaskBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 375, -1, -1));

        DeleteBackBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back.png"))); // NOI18N
        DeleteBackBtn.setPreferredSize(new java.awt.Dimension(50, 50));
        DeleteBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBackBtnActionPerformed(evt);
            }
        });
        DeleteTaskPnl.add(DeleteBackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));

        DeleteFowardBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foward.png"))); // NOI18N
        DeleteFowardBtn.setPreferredSize(new java.awt.Dimension(50, 50));
        DeleteTaskPnl.add(DeleteFowardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, -1, -1));

        DeleteTaskBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lightThemeIcons/BACKGROUND.png"))); // NOI18N
        DeleteTaskBG.setToolTipText("");
        DeleteTaskPnl.add(DeleteTaskBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 450, 550));

        getContentPane().add(DeleteTaskPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        MarkDoneTaskIcn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/done.png"))); // NOI18N
        MarkDoneTaskIcn.setToolTipText("Mark Done");
        MarkDoneTaskIcn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MarkDoneTaskIcnMouseClicked(evt);
            }
        });
        getContentPane().add(MarkDoneTaskIcn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 390, -1, -1));

        MarkDonePnl.setPreferredSize(new java.awt.Dimension(350, 500));
        MarkDonePnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MarkDoneSearchFld.setBackground(new Color(40,40,40,128));
        MarkDoneSearchFld.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MarkDoneSearchFld.setForeground(new java.awt.Color(255, 255, 255));
        MarkDoneSearchFld.setToolTipText("Search");
        MarkDoneSearchFld.setPreferredSize(new java.awt.Dimension(150, 30));
        MarkDoneSearchFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarkDoneSearchFldActionPerformed(evt);
            }
        });
        MarkDoneSearchFld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MarkDoneSearchFldKeyTyped(evt);
            }
        });
        MarkDonePnl.add(MarkDoneSearchFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Task ID        :");
        jLabel1.setPreferredSize(new java.awt.Dimension(380, 40));
        MarkDonePnl.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        TaskNamelbl2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TaskNamelbl2.setText("Task Name :");
        TaskNamelbl2.setPreferredSize(new java.awt.Dimension(110, 30));
        MarkDonePnl.add(TaskNamelbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 380, 40));

        Subjectlbl2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Subjectlbl2.setText("Subject       :");
        Subjectlbl2.setPreferredSize(new java.awt.Dimension(120, 40));
        MarkDonePnl.add(Subjectlbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 380, -1));

        DueDatelbl2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DueDatelbl2.setText("Due Date    :");
        DueDatelbl2.setPreferredSize(new java.awt.Dimension(110, 40));
        MarkDonePnl.add(DueDatelbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 380, -1));

        DueTime2.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        DueTime2.setText("Due Time    :");
        DueTime2.setPreferredSize(new java.awt.Dimension(110, 40));
        MarkDonePnl.add(DueTime2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 380, -1));

        Prioritylbl2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Prioritylbl2.setText("Priority      :");
        Prioritylbl2.setPreferredSize(new java.awt.Dimension(98, 40));
        MarkDonePnl.add(Prioritylbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 380, 40));

        Statuslbl2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Statuslbl2.setText("Status        :");
        MarkDonePnl.add(Statuslbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 380, 40));

        MarkDoneBackBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back.png"))); // NOI18N
        MarkDoneBackBtn.setPreferredSize(new java.awt.Dimension(50, 50));
        MarkDonePnl.add(MarkDoneBackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        MarkDoneBtn.setBackground(new Color(40,40,40,128));
        MarkDoneBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MarkDoneBtn.setText("Mark Done");
        MarkDoneBtn.setPreferredSize(new java.awt.Dimension(150, 40));
        MarkDonePnl.add(MarkDoneBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 405, -1, -1));

        MarkDoneFowardBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foward.png"))); // NOI18N
        MarkDoneFowardBtn.setPreferredSize(new java.awt.Dimension(50, 50));
        MarkDonePnl.add(MarkDoneFowardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, -1, -1));

        MarkDoneBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lightThemeIcons/BACKGROUND.png"))); // NOI18N
        MarkDoneBG.setToolTipText("");
        MarkDonePnl.add(MarkDoneBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 450, 550));

        getContentPane().add(MarkDonePnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        TaskFrameBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lightThemeIcons/BACKGROUND.png"))); // NOI18N
        TaskFrameBG.setToolTipText("");
        TaskFrameBG.setPreferredSize(new java.awt.Dimension(700, 550));
        getContentPane().add(TaskFrameBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddTaskBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTaskBtnActionPerformed
        // TODO add your handling code here:
        try {
            // Generate a unique ID for the new task. Using the current time in milliseconds is a simple way to do this.
            int taskID = (int) (new Date().getTime() / 1000);

            // Get and validate the task name.
            String taskName = TaskName.getText().trim();
            if (taskName.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter a task name.",
                        "Input Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Get and validate the subject.
            String subject = Subject.getText().trim();
            if (subject.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter a subject.",
                        "Input Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Get and validate the due date.
            Date dueDate = DateChooser.getDate();
            if (dueDate == null) {
                JOptionPane.showMessageDialog(this, "Please select a due date.",
                        "Input Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Use the TaskUtils.formatDate() method
            String formattedDate = TaskUtils.formatDate(dueDate);
            System.out.println("Task due date: " + formattedDate);

            String hour = (String) HourChooser.getSelectedItem();
            String minute = (String) MinuteChooser.getSelectedItem();

            // Use the TaskUtils.formatTime() method
            String dueTime = TaskUtils.formatTime(hour, minute);
            System.out.println("Task due time: " + dueTime);

            // Get the selected priority and status.
            String priority = (String) PriorityChooser.getSelectedItem();
            String status = (String) StatusChooser.getSelectedItem();

            // Convert the Date to LocalDate and hour/minute to LocalTime for the Task object.
            LocalDate localDueDate = dueDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            LocalTime localDueTime = LocalTime.of(Integer.parseInt(hour), Integer.parseInt(minute));

            // Create a new Task object with the collected data.
            Task newTask = new Task(taskID, taskName, subject, localDueDate, localDueTime, priority, status);

            // Add the new task to the TaskManager.
            taskManager.addTask(newTask);

            // Write the entire updated task list to the file
            fileHandler.writeToTaskFile(taskManager.getTaskList());

            clearInputFields();
            JOptionPane.showMessageDialog(this, "Task added and saved successfully!",
                    "Success", JOptionPane.INFORMATION_MESSAGE);
            
            this.dispose();

        } catch (Exception e) {
            // Catch any potential errors and display an error message.
            JOptionPane.showMessageDialog(this, "Error adding task: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

    }//GEN-LAST:event_AddTaskBtnActionPerformed

    private void AddTaskIcnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddTaskIcnMouseClicked
        // TODO add your handling code here:
        themeManager.showAddTaskPanel(AddTaskPnl, EditTaskPnl, DeleteTaskPnl, MarkDonePnl);
        setPanel(AddTaskPnl, new Dimension(450, 500));
    }//GEN-LAST:event_AddTaskIcnMouseClicked

    private void EditTaskIcnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditTaskIcnMouseClicked
        // TODO add your handling code here:
        themeManager.showEditTaskPanel(AddTaskPnl, EditTaskPnl, DeleteTaskPnl, MarkDonePnl);
        setPanel(EditTaskPnl, new Dimension(800, 500));
    }//GEN-LAST:event_EditTaskIcnMouseClicked

    private void DeleteTaskIcnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteTaskIcnMouseClicked
        // TODO add your handling code here:
        themeManager.showDeleteTaskPanel(AddTaskPnl, EditTaskPnl, DeleteTaskPnl, MarkDonePnl);
        setPanel(DeleteTaskPnl, new Dimension(450, 550));
    }//GEN-LAST:event_DeleteTaskIcnMouseClicked

    private void MarkDoneTaskIcnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MarkDoneTaskIcnMouseClicked
        // TODO add your handling code here:
        themeManager.showMarkDonePanel(AddTaskPnl, EditTaskPnl, DeleteTaskPnl, MarkDonePnl);
        setPanel(MarkDonePnl, new Dimension(450, 550));
    }//GEN-LAST:event_MarkDoneTaskIcnMouseClicked

    private void EditTaskSearchFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditTaskSearchFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditTaskSearchFldActionPerformed

    private void EditTaskSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditTaskSearchBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditTaskSearchBtnActionPerformed

    private void EditTaskBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditTaskBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditTaskBtnActionPerformed

    private void DeleteTaskSearchFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteTaskSearchFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteTaskSearchFldActionPerformed

    private void DeleteTaskBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteTaskBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteTaskBtnActionPerformed

    private void DeleteBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBackBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteBackBtnActionPerformed

    private void MarkDoneSearchFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarkDoneSearchFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MarkDoneSearchFldActionPerformed

    private void MarkDoneSearchFldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MarkDoneSearchFldKeyTyped
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {}
    }//GEN-LAST:event_MarkDoneSearchFldKeyTyped

    private void clearInputFields() {
        TaskName.setText("");
        Subject.setText("");
        DateChooser.setDate(null);
        HourChooser.setSelectedIndex(0);
        MinuteChooser.setSelectedIndex(0);
        PriorityChooser.setSelectedIndex(0);
        StatusChooser.setSelectedIndex(0);
    }

    private void setPanel(JPanel panelToShow, Dimension frameSize) {
        AddTaskPnl.setVisible(false);
        EditTaskPnl.setVisible(false);
        DeleteTaskPnl.setVisible(false);
        MarkDonePnl.setVisible(false);

        panelToShow.setVisible(true);
        this.setPreferredSize(frameSize);
        this.setSize(frameSize);
        this.pack();
        this.setLocationRelativeTo(null);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaskFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaskFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaskFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaskFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
            SwingUtilities.updateComponentTreeUI(new MainMenu());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaskFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddTaskBG;
    private javax.swing.JButton AddTaskBtn;
    private javax.swing.JLabel AddTaskIcn;
    private javax.swing.JPanel AddTaskPnl;
    private javax.swing.JLabel BG1;
    private com.toedter.calendar.JDateChooser DateChooser;
    private javax.swing.JButton DeleteBackBtn;
    private javax.swing.JButton DeleteFowardBtn;
    private javax.swing.JLabel DeleteTaskBG;
    private javax.swing.JButton DeleteTaskBtn;
    private javax.swing.JLabel DeleteTaskIcn;
    private javax.swing.JPanel DeleteTaskPnl;
    private javax.swing.JTextField DeleteTaskSearchFld;
    private javax.swing.JLabel DueDatelbl;
    private javax.swing.JLabel DueDatelbl1;
    private javax.swing.JLabel DueDatelbl2;
    private javax.swing.JLabel DueTime;
    private javax.swing.JLabel DueTime1;
    private javax.swing.JLabel DueTime2;
    private javax.swing.JButton EditTaskBtn;
    private javax.swing.JLabel EditTaskIcn;
    private javax.swing.JPanel EditTaskPnl;
    private javax.swing.JButton EditTaskSearchBtn;
    private javax.swing.JTextField EditTaskSearchFld;
    private javax.swing.JComboBox<String> HourChooser;
    private javax.swing.JLabel MarkDoneBG;
    private javax.swing.JButton MarkDoneBackBtn;
    private javax.swing.JButton MarkDoneBtn;
    private javax.swing.JButton MarkDoneFowardBtn;
    private javax.swing.JPanel MarkDonePnl;
    private javax.swing.JTextField MarkDoneSearchFld;
    private javax.swing.JLabel MarkDoneTaskIcn;
    private javax.swing.JComboBox<String> MinuteChooser;
    private javax.swing.JComboBox<String> PriorityChooser;
    private javax.swing.JLabel Prioritylbl;
    private javax.swing.JLabel Prioritylbl1;
    private javax.swing.JLabel Prioritylbl2;
    private javax.swing.JComboBox<String> StatusChooser;
    private javax.swing.JLabel Statuslbl;
    private javax.swing.JLabel Statuslbl1;
    private javax.swing.JLabel Statuslbl2;
    private javax.swing.JTextField Subject;
    private javax.swing.JLabel Subjectlbl;
    private javax.swing.JLabel Subjectlbl1;
    private javax.swing.JLabel Subjectlbl2;
    private javax.swing.JLabel TaskFrameBG;
    private javax.swing.JTextField TaskName;
    private javax.swing.JLabel TaskNamelbl;
    private javax.swing.JLabel TaskNamelbl1;
    private javax.swing.JLabel TaskNamelbl2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
