package UI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import Managers.Authenticator;
import Managers.ThemeManager;
import javax.swing.*;

public class LoginPage extends javax.swing.JFrame {
    Authenticator a = new Authenticator();
    ThemeManager tm = new ThemeManager();
    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        
        setLocationRelativeTo(null);
        setResizable(false);

        applyFuncCos();
        PasswordFld.setEchoChar('•');
        
    }
    
    private void applyFuncCos() {

        tm.transparentButton(LoginBtn);

        tm.transparentTextField(UsernameFld);
        tm.transparentPasswordField(PasswordFld);
        a.addLoginExitListeners(this, UsernameFld, PasswordFld);
        
        
        // Add placeholders
        tm.addPlaceholder(UsernameFld, "Username");
        tm.addPlaceholder(PasswordFld, "Password");

        // Attach toggle functionality with icons
        String showIconPath = getClass().getResource("/visible.png").getPath();
        String hideIconPath = getClass().getResource("/invisible.png").getPath();

        ImageIcon showIcon = ThemeManager.ResizeImage(showIconPath, 24, 24);
        ImageIcon hideIcon = ThemeManager.ResizeImage(hideIconPath, 24, 24);

        tm.addPasswordToggle(PasswordFld, ToggleBtn, showIcon, hideIcon);
        tm.toggle(ToggleBtn);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginPnl = new javax.swing.JPanel();
        UsernameFld = new javax.swing.JTextField();
        PasswordFld = new javax.swing.JPasswordField();
        LoginBtn = new javax.swing.JButton();
        ToggleBtn = new javax.swing.JToggleButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));

        LoginPnl.setOpaque(false);
        LoginPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UsernameFld.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        UsernameFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameFldActionPerformed(evt);
            }
        });
        LoginPnl.add(UsernameFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 235, 330, 43));

        PasswordFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFldActionPerformed(evt);
            }
        });
        LoginPnl.add(PasswordFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 300, 330, 43));

        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });
        LoginPnl.add(LoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 120, 40));

        ToggleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleBtnActionPerformed(evt);
            }
        });
        LoginPnl.add(ToggleBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 40, 40));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginPage.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Background)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Background)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        // TODO add your handling code here:      
        a.handleLoginAction(this, UsernameFld, PasswordFld);
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void UsernameFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameFldActionPerformed

    private void PasswordFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFldActionPerformed

    private void ToggleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToggleBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JPanel LoginPnl;
    private javax.swing.JPasswordField PasswordFld;
    private javax.swing.JToggleButton ToggleBtn;
    private javax.swing.JTextField UsernameFld;
    // End of variables declaration//GEN-END:variables
}
